Basic Arithmetical Properties

In [1]:
import numpy as np

In [2]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [4]:

X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [5]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [6]:
import torch

In [7]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [8]:
X_pt*2+2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [9]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [10]:
import tensorflow as tf

In [11]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [12]:
X_tf*2+2 # Operators likewise overloaded; could equally use tf.multiply() tf.add()

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [13]:
tf.add(tf.multiply(X_tf, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [14]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [15]:
A = X+2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [16]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [17]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [18]:
A_pt = X_pt + 2

In [19]:
A_pt + X_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [20]:
A_pt * X_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [21]:
A_tf = X_tf + 2

In [22]:
A_tf + X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [23]:
A_tf * X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]])>

Reduction

In [24]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [25]:

X.sum()

68

In [26]:
torch.sum(X_pt)

tensor(68)

In [27]:

tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [28]:
# Can also be done along one specific axis alone, e.g.:
X.sum(axis=0) #COLUMN SUM

array([33, 35])

In [29]:
X.sum(axis=1)

array([27, 31, 10])

In [30]:
torch.sum(X_pt, 0)

tensor([33, 35])

In [31]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10])>