In [1]:
import numpy as np 
a=np.array([0,1,2,3])
print(a)
print(np.arange(10))


[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
a=np.arange(1000)
%timeit a**2

4.12 µs ± 790 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
#1D
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [4]:
#print dimension
a.ndim

1

In [5]:
#shape
a.shape

(4,)

In [6]:
len(a)

4

In [7]:
#2D , 3D
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
len(b) #returns the size of the first direction

2

In [11]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
c.ndim

3

In [13]:
c.shape

(2, 2, 2)

In [14]:
#using arange function
#arrange is an array-valued version of the built-in python range function
a=np.arange(10)  #0......(n-1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b=np.arange(1,10,2) # start, end , step
b

array([1, 3, 5, 7, 9])

In [16]:
#using linespace
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
#common arrays
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
c=np.eye(3)    # return  a 2-D array with ones on the diagonal and zeroes elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# create array using diag function
a=np.diag([1,2,3,4])  #construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
np.diag(a)  #extract diagonal

array([1, 2, 3, 4])

In [22]:
# create array using random
#create an array of the given shape and populate it with random samples from a uniform distribution
a=np.random.rand(4)
a 

array([0.8203302 , 0.2216412 , 0.97811294, 0.47430002])

In [25]:
a=np.random.randn(4)  #return a sample from the "standard normal" distribution. ***gausion value***
a

array([ 0.12949613,  0.82689968,  0.88710576, -0.86393939])

In [26]:
a=np.arange(10)
a.dtype

dtype('int32')

In [27]:
# you can explicitly specify which data type you want :
a=np.arange(10,dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
# the default data type is float for zeros and ones function
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [29]:
d=np.array([1+2j,2+4j])  #complex data type
print(d.dtype)


complex128


In [36]:
b=np.array([True, False, True, False])  #boolean datatype
print(b.dtype)

bool


In [37]:
a=np.arange(10)
print(a[5])   #starts with zero  

5


In [39]:
# for multidimensional arrays, indexes are tuples of integers
a=np.diag([1,2,3])
print(a)
print(a[2,2])   # row column ke form par work nhi krta 0 se counting start krte hai

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [41]:
a[2,1] = 4  #assining value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 4, 3]])

In [42]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a[1:8:2]  #start:end:step

array([1, 3, 5, 7])

In [44]:
# we can also combine assignment and slicing
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [45]:
b=np.arange(5)
a[5:]= b[::-1]  #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [46]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [48]:
np.shares_memory(a,b)

True

In [49]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [50]:
a #although we modified b, it updated 'a' because both shares same memory


array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [51]:
a=np.arange(10)
c=a[::2].copy()  # force a copy
c 

array([0, 2, 4, 6, 8])

In [52]:
np.shares_memory(a,b)

False

In [53]:
c[0]=10
a    #this is showing at memory  a is different and c is different

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a=np.random.randint(0, 20, 15)
a

array([10, 18, 15,  2,  7,  0, 19, 11, 12,  2,  4,  8, 10,  6,  2])

In [58]:
mask=(a%2==0)

In [59]:
extract_from_a = a[mask]
extract_from_a 

array([10, 18,  2,  0, 12,  2,  4,  8, 10,  6,  2])

In [60]:
a[mask]=-1
a

array([-1, -1, 15, -1,  7, -1, 19, 11, -1, -1, -1, -1, -1, -1, -1])

In [61]:
a=np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
# indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [65]:
# new values can be assigned
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [66]:
a=np.array([1,2,3,4])  #create an array
a+1

array([2, 3, 4, 5])

In [67]:
a**2

array([ 1,  4,  9, 16])

In [68]:
b=np.ones(4)+1
print(b)
print(a-b)

[2. 2. 2. 2.]
[-1.  0.  1.  2.]


In [69]:
a*b

array([2., 4., 6., 8.])

In [70]:
#matrix multiplication
c=np.diag([1,2,3,4])
print(c*c)
print("********")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
