In [2]:
import numpy as np 
a=np.array([0,1,2,3])
print(a)
print(np.arange(10))


[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
a=np.arange(1000)
%timeit a**2

4.47 µs ± 551 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
#1D
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [5]:
#print dimension
a.ndim

1

In [6]:
#shape
a.shape

(4,)

In [7]:
len(a)

4

In [8]:
#2D , 3D
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
len(b) #returns the size of the first direction

2

In [12]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
c.ndim

3

In [14]:
c.shape

(2, 2, 2)

In [15]:
#using arange function
#arrange is an array-valued version of the built-in python range function
a=np.arange(10)  #0......(n-1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b=np.arange(1,10,2) # start, end , step
b

array([1, 3, 5, 7, 9])

In [17]:
#using linespace
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
#common arrays
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
c=np.eye(3)    # return  a 2-D array with ones on the diagonal and zeroes elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# create array using diag function
a=np.diag([1,2,3,4])  #construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
np.diag(a)  #extract diagonal

array([1, 2, 3, 4])

In [23]:
# create array using random
#create an array of the given shape and populate it with random samples from a uniform distribution
a=np.random.rand(4)
a 

array([0.01157913, 0.03769494, 0.82924415, 0.41608691])