In [2]:
import numpy as np 
a=np.array([0,1,2,3])
print(a)
print(np.arange(10))


[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
a=np.arange(1000)
%timeit a**2

3.28 µs ± 493 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
#1D
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [6]:
#print dimension
a.ndim

1

In [7]:
#shape
a.shape

(4,)

In [8]:
len(a)

4

In [10]:
#2D , 3D
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [13]:
len(b) #returns the size of the first direction

2

In [18]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
c.ndim

3

In [21]:
c.shape

(2, 2, 2)