In [2]:
import numpy as np 
a=np.array([0,1,2,3])
print(a)
print(np.arange(10))


[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
a=np.arange(1000)
%timeit a**2

3.58 µs ± 519 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
#1D
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [5]:
#print dimension
a.ndim

1

In [6]:
#shape
a.shape

(4,)

In [7]:
len(a)

4

In [8]:
#2D , 3D
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
len(b) #returns the size of the first direction

2

In [12]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
c.ndim

3

In [14]:
c.shape

(2, 2, 2)

In [15]:
#using arange function
#arrange is an array-valued version of the built-in python range function
a=np.arange(10)  #0......(n-1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b=np.arange(1,10,2) # start, end , step
b

array([1, 3, 5, 7, 9])

In [17]:
#using linespace
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
#common arrays
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
c=np.eye(3)    # return  a 2-D array with ones on the diagonal and zeroes elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# create array using diag function
a=np.diag([1,2,3,4])  #construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
np.diag(a)  #extract diagonal

array([1, 2, 3, 4])

In [23]:
# create array using random
#create an array of the given shape and populate it with random samples from a uniform distribution
a=np.random.rand(4)
a 

array([0.21999255, 0.10307366, 0.62092914, 0.91906434])

In [24]:
a=np.random.randn(4)  #return a sample from the "standard normal" distribution. ***gausion value***
a

array([1.10661932, 1.01108749, 0.39193481, 0.27268077])

In [25]:
a=np.arange(10)
a.dtype

dtype('int32')

In [26]:
# you can explicitly specify which data type you want :
a=np.arange(10,dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
# the default data type is float for zeros and ones function
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [28]:
d=np.array([1+2j,2+4j])  #complex data type
print(d.dtype)


complex128


In [29]:
b=np.array([True, False, True, False])  #boolean datatype
print(b.dtype)

bool


In [30]:
a=np.arange(10)
print(a[5])   #starts with zero  

5


In [31]:
# for multidimensional arrays, indexes are tuples of integers
a=np.diag([1,2,3])
print(a)
print(a[2,2])   # row column ke form par work nhi krta 0 se counting start krte hai

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [32]:
a[2,1] = 4  #assining value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 4, 3]])

In [33]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[1:8:2]  #start:end:step

array([1, 3, 5, 7])

In [35]:
# we can also combine assignment and slicing
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [36]:
b=np.arange(5)
a[5:]= b[::-1]  #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [37]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [39]:
np.shares_memory(a,b)

True

In [40]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [41]:
a #although we modified b, it updated 'a' because both shares same memory


array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [42]:
a=np.arange(10)
c=a[::2].copy()  # force a copy
c 

array([0, 2, 4, 6, 8])

In [43]:
np.shares_memory(a,b)

False

In [44]:
c[0]=10
a    #this is showing at memory  a is different and c is different

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a=np.random.randint(0, 20, 15)
a

array([ 3,  7, 11,  4, 13, 11,  1, 18,  4,  6,  5, 10,  6, 14,  0])

In [46]:
mask=(a%2==0)

In [47]:
extract_from_a = a[mask]
extract_from_a 

array([ 4, 18,  4,  6, 10,  6, 14,  0])

In [48]:
a[mask]=-1
a

array([ 3,  7, 11, -1, 13, 11,  1, -1, -1, -1,  5, -1, -1, -1, -1])

In [49]:
a=np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
# indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [51]:
# new values can be assigned
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [52]:
a=np.array([1,2,3,4])  #create an array
a+1

array([2, 3, 4, 5])

In [53]:
a**2

array([ 1,  4,  9, 16])

In [54]:
b=np.ones(4)+1
print(b)
print(a-b)

[2. 2. 2. 2.]
[-1.  0.  1.  2.]


In [55]:
a*b

array([2., 4., 6., 8.])

In [56]:
#matrix multiplication
c=np.diag([1,2,3,4])
print(c*c)
print("********")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


comparisions

In [57]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [58]:
a>b

array([False, False,  True, False])

In [59]:
# array wise comparisions
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])
np.array_equal(a,b)

False

In [60]:
np.array_equal(a,c)

True

Logical operation

In [61]:
a=np.array([1,1,0,0], dtype=bool)
b=np.array([1,0,0,1], dtype=bool)
np.logical_or(a,b)


array([ True,  True, False,  True])

In [62]:
np.logical_and(a,b)


array([ True, False, False, False])

Transcendental function

In [63]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [64]:
np.log(a)

C:\Users\Asus\AppData\Local\Temp\ipykernel_16824\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [65]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

Shape mismatch

in matrix if we don't give same dimension we can't perform addition, substraction

In [66]:
a=np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

DAY 19
Basic reduction

computing sums

In [ ]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [ ]:
#sum by rows and by columns
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum(axis=0)  #column first dimension


array([3, 3])

In [ ]:
x.sum(axis=1)  #rows(second dimension)

array([2, 4])

other reduction

In [ ]:
x=np.array([1,3,2])
x.min()

1

In [ ]:
x.max()

3

In [ ]:
x.argmin()  #index of minimum element

0

In [ ]:
x.argmax()  #index of maximum element

1

Logical operation

In [ ]:
np.all([True, True, False])  #like and gate


False

In [ ]:
np.any([True, True, False])  #like or gate

True

In [ ]:
#note: can be used for array comparisions
a = np.zeros((50,50))
np.any(a != 0)

False

In [ ]:
np.all(a==a)

True

In [ ]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b)& (b<=c)).all()

True

Statistics

In [ ]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,7]])
x.mean()

1.75

In [ ]:
np.median(x)

1.5

In [ ]:
np.median(y, axis=-1)  #last axis


array([2., 6.])

In [ ]:
x.std()

0.82915619758885

Example

data in populations txt describes the populations of hares and lynxes (and carrots) in northern canada during 20 years