2x2 Matrix Determinants


In [1]:
import numpy as np

In [2]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [3]:
np.linalg.det(X)

-2.0000000000000013

In [4]:
N = np.array([[-4, 1], [-8, 2]])
N

array([[-4,  1],
       [-8,  2]])

In [5]:
np.linalg.det(N)

0.0

In [ ]:
# Uncommenting the following line results in a "singular matrix" error
# Ninv = np.linalg.inv(N)

In [7]:
import torch

In [8]:
N = torch.tensor([[-4, 1], [-8, 2.]]) # must use float not int

In [9]:
torch.det(N) 

tensor(-0.)

Generalizing Determinants

In [10]:
X = np.array([[1, 2, 4], [2, -1, 3], [0, 5, 1]])
X

array([[ 1,  2,  4],
       [ 2, -1,  3],
       [ 0,  5,  1]])

In [11]:
np.linalg.det(X)

19.999999999999996