In [2]:
import numpy as np

In [3]:
v=np.array([25,2,-3,-23])

In [4]:
v

array([ 25,   2,  -3, -23])

In [5]:
v.T # transpose

array([ 25,   2,  -3, -23])

In [6]:
mat=np.array([[42,4,7,99],[-99,-3,17,22]])

In [7]:
mat

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [8]:
mat.ndim

2

what is the position of the element in the matrix  with the value of 17

In [9]:
np.where(mat == 17)



(array([1], dtype=int64), array([2], dtype=int64))

In [10]:
y=np.array([[42,4,7,99],[-99,-3,17,22]])

In [11]:
y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [12]:
y.T #transpose

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [13]:
x=np.array([[25,10],[-2,1]])

In [14]:
y=np.array([[-1,7],[10,8]])

Hadamard product or simply the element-wise product.

In [15]:
x*y

array([[-25,  70],
       [-20,   8]])

In [16]:
w=np.array([-1,3,-2])

In [17]:
x=np.array([5,10,0])

In [18]:
np.dot(w,x)

25

Matrix Multiplication

In [22]:
import torch

In [23]:
M_q = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
M_q

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [24]:
V_q = torch.tensor([[-1, 1, -2], [0, 1, 2]]).T
V_q

tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])

In [25]:
torch.matmul(M_q, V_q)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])