In [1]:
import numpy as np

In [2]:
v=np.array([25,2,-3,-23])

In [3]:
v

array([ 25,   2,  -3, -23])

In [4]:
v.T # transpose

array([ 25,   2,  -3, -23])

In [6]:
mat=np.array([[42,4,7,99],[-99,-3,17,22]])

In [7]:
mat

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [9]:
mat.ndim

2

what is the position of the element in the matrix  with the value of 17

In [14]:
np.where(mat == 17)



(array([1], dtype=int64), array([2], dtype=int64))