In [1]:
import numpy as np

In [2]:
v=np.array([25,2,-3,-23])

In [3]:
v

array([ 25,   2,  -3, -23])

In [4]:
v.T # transpose

array([ 25,   2,  -3, -23])

In [6]:
mat=np.array([[42,4,7,99],[-99,-3,17,22]])

In [7]:
mat

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [9]:
mat.ndim

2

what is the position of the element in the matrix  with the value of 17

In [14]:
np.where(mat == 17)



(array([1], dtype=int64), array([2], dtype=int64))

In [15]:
y=np.array([[42,4,7,99],[-99,-3,17,22]])

In [16]:
y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [17]:
y.T #transpose

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [18]:
x=np.array([[25,10],[-2,1]])

In [19]:
y=np.array([[-1,7],[10,8]])

Hadamard product or simply the element-wise product.

In [21]:
x*y

array([[-25,  70],
       [-20,   8]])

In [22]:
w=np.array([-1,3,-2])

In [23]:
x=np.array([5,10,0])

In [25]:
np.dot(w,x)

25