Matrices (Rank 2 Tensors) in NumPy

In [1]:
import numpy as np

In [2]:
# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

In [5]:
# Select left column of matrix X (zero-indexed)
X[:,0] # := all row , 0= first column

array([25,  5,  3])

In [6]:
# Select middle row of matrix X: 
X[1,:]

array([ 5, 26])

In [7]:
# Another slicing-by-index example: 
X[0:2, 0:2] #first row second row first col second col

array([[25,  2],
       [ 5, 26]])

Matrices in PyTorch

In [8]:
import torch

In [9]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [10]:
X_pt.shape

torch.Size([3, 2])

In [11]:
X_pt[1,:]

tensor([ 5, 26])

Matrices in TensorFlow

In [12]:
import tensorflow as tf

In [13]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [14]:
tf.rank(X_tf) #rank=dimension

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [16]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>

Segment 3: Matrix Properties

Frobenius Norm

In [17]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [18]:
(1**2 + 2**2 + 3**2 + 4**2)**(1/2)

5.477225575051661

In [19]:
np.linalg.norm(X) # same function as for vector L2 norm

5.477225575051661

In [20]:
X_pt = torch.tensor([[1, 2], [3, 4.]]) # torch.norm() supports floats only

In [21]:
torch.norm(X_pt)

tensor(5.4772)

In [22]:
X_tf = tf.Variable([[1, 2], [3, 4.]]) # tf.norm() also supports floats only

In [23]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>

Matrix Multiplication (with a Vector)

In [24]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [25]:
b = np.array([1, 2])
b

array([1, 2])

In [26]:
np.dot(A, b) # even though technically dot products are between vectors only

array([11, 17, 23])

In [27]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [28]:
b_pt = torch.tensor([1, 2])
b_pt

tensor([1, 2])

In [29]:
torch.matmul(A_pt, b_pt) # like np.dot(), automatically infers dims in order to perform dot product, matvec, or matrix multiplication

tensor([11, 17, 23])

In [30]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]])>

In [31]:
b_tf = tf.Variable([1, 2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [32]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23])>

Matrix Multiplication (with Two Matrices)

In [33]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [34]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [35]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

Note that matrix multiplication is not "commutative" (i.e.,  AB≠BA ) so uncommenting the following line will throw a size mismatch error:



In [36]:
#np.dot(B, A)

In [37]:
B_pt = torch.from_numpy(B) # much cleaner than TF conversion
B_pt

tensor([[1, 9],
        [2, 0]], dtype=torch.int32)

In [38]:
# another neat way to create the same tensor with transposition: 
B_pt = torch.tensor([[1, 2], [9, 0]]).T
B_pt

tensor([[1, 9],
        [2, 0]])

In [39]:
torch.matmul(A_pt, B_pt) # no need to change functions, unlike in TF

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [40]:
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [2, 0]])>

In [41]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]])>

Symmetric Matrices

In [42]:
X_sym = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [43]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [44]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Identity Matrices

In [45]:
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [46]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [47]:
torch.matmul(I, x_pt)

tensor([25,  2,  5])

Matrix Inversion

In [48]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [49]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

let's prove that (X**-1)*X

In [50]:
np.dot(Xinv, X)

array([[1.00000000e+00, 3.33066907e-16],
       [0.00000000e+00, 1.00000000e+00]])

and now back to solving for the unknowns in  w :

In [51]:
y = np.array([4, -7])
y

array([ 4, -7])

In [52]:
w = np.dot(Xinv, y)
w

array([-1.,  4.])

Show that $y = Xw 


In [53]:
np.dot(X, w)

array([ 4., -7.])

In [54]:
torch.inverse(torch.tensor([[4, 2], [-5, -3.]])) # float type

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [55]:
tf.linalg.inv(tf.Variable([[4, 2], [-5, -3.]])) # also float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999998,  0.9999998],
       [-2.4999995, -1.9999996]], dtype=float32)>

Orthogonal Matrices


In [56]:
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
column_1 = I[:,0]
column_1

array([1, 0, 0])

In [58]:
column_2 = I[:,1]
column_2

array([0, 1, 0])

In [59]:
column_3 = I[:,2]
column_3

array([0, 0, 1])

In [60]:
np.dot(column_1, column_2)

0

In [61]:
np.dot(column_1, column_3)

0

In [62]:
np.dot(column_2, column_3)

0

We can use the np.linalg.norm() method from earlier in the notebook to demonstrate that each column of  I3  has unit norm:

In [63]:
np.linalg.norm(column_1)

1.0

In [64]:
np.linalg.norm(column_2)

1.0

In [65]:
np.linalg.norm(column_3)

1.0