Matrices (Rank 2 Tensors) in NumPy

In [1]:
import numpy as np

In [2]:
# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

In [5]:
# Select left column of matrix X (zero-indexed)
X[:,0] # := all row , 0= first column

array([25,  5,  3])

In [6]:
# Select middle row of matrix X: 
X[1,:]

array([ 5, 26])

In [7]:
# Another slicing-by-index example: 
X[0:2, 0:2] #first row second row first col second col

array([[25,  2],
       [ 5, 26]])

Matrices in PyTorch

In [9]:
import torch

In [10]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [11]:
X_pt.shape

torch.Size([3, 2])

In [12]:
X_pt[1,:]

tensor([ 5, 26])

Matrices in TensorFlow

In [13]:
import tensorflow as tf

In [14]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [15]:
tf.rank(X_tf) #rank=dimension

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [16]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [17]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>