In [1]:
import numpy as np

In [2]:
x = np.array([25, 2, 5]) 
x

array([25,  2,  5])

In [3]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [4]:
np.linalg.norm(x) #linear algebra

25.573423705088842

So, if units in this 3-dimensional vector space are meters, then the vector 
 has a length of 25.6m

L Norm

In [5]:
x

array([25,  2,  5])

In [6]:
np.abs(25) + np.abs(2) + np.abs(5)  #absolute value

32

Squared L**2 Norm

In [7]:
x

array([25,  2,  5])

In [8]:
(25**2 + 2**2 + 5**2)

654

In [9]:
np.dot(x, x)

654

Max Norm

In [10]:
x

array([25,  2,  5])

In [11]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25