The Moore-Penrose Pseudoinverse

Let's calculate the pseudoinverse  A+  of some matrix  A  using the formula from the slides:

A+=VD+UT

In [1]:
import numpy as np

In [2]:
A = np.array([[-1, 2], [3, -2], [5, 7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

As shown earlier, the NumPy SVD method returns  U ,  d , and  VT :

In [3]:
U, d, VT = np.linalg.svd(A)

In [4]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [5]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [6]:
d

array([8.66918448, 4.10429538])

To create  D+ , we first invert the non-zero values of  d :

In [7]:
D = np.diag(d)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [8]:
1/8.669

0.11535355865728457

In [9]:
1/4.104

0.24366471734892786

and then we would take the tranpose of the resulting matrix.

Because  D  is a diagonal matrix, this can, however, be done in a single step by inverting  D :

In [10]:
Dinv = np.linalg.inv(D)
Dinv

array([[0.1153511 , 0.        ],
       [0.        , 0.24364718]])

D+  must have the same dimensions as AT in order for VD+UT matrix multiplication to be possible:

In [11]:
Dplus = np.concatenate((Dinv, np.array([[0, 0]]).T), axis=1)
Dplus

array([[0.1153511 , 0.        , 0.        ],
       [0.        , 0.24364718, 0.        ]])

(Recall  D  must have the same dimensions as  A  for SVD's  UDVT , but for MPP  U  and  V  have swapped sides around the diagonal matrix.)

Now we have everything we need to calculate  A+  with  VD+UT :

In [12]:
np.dot(VT.T, np.dot(Dplus, U.T))

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

Working out this derivation is helpful for understanding how Moore-Penrose pseudoinverses work, but unsurprisingly NumPy is loaded with an existing method pinv():

In [13]:
np.linalg.pinv(A)

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

in pytorch

In [15]:
import torch

In [16]:
A_p = torch.tensor([[-1, 2], [3, -2], [5, 7.]])
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [17]:
torch.pinverse(A_p)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])