Singular Value Decomposition (SVD)


SVD of matrix  A  is:

A=UDV**T

Where:

U  is an orthogonal  m×m  matrix; its columns are the left-singular vectors of  A .
V  is an orthogonal  n×n  matrix; its columns are the right-singular vectors of  A .
D  is a diagonal  m×n  matrix; elements along its diagonal are the singular values of  A .

In [1]:
import numpy as np

In [2]:
A = np.array([[-1, 2], [3, -2], [5, 7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [3]:
U, d, VT = np.linalg.svd(A) # V is already transposed

In [4]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [5]:
d

array([8.66918448, 4.10429538])

In [6]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

D  must have the same dimensions as A for UDVT matrix multiplication to be possible:

In [7]:
D = np.concatenate((np.diag(d), [[0, 0]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [8]:
np.dot(U, np.dot(D, VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])