Vectors (Rank 1 Tensors) in NumPy

In [2]:
import numpy as np

In [3]:
x = np.array([25, 2, 5]) 
x

array([25,  2,  5])

In [6]:
len(x)

3

In [7]:
x.shape

(3,)

In [8]:
type(x)

numpy.ndarray

In [9]:
x[0] # zero-indexed

25

In [10]:
type(x[0])

numpy.int32

Vector Transposition

In [11]:
# Transposing a regular 1-D array has no effect...
x_t = x.T
x_t

array([25,  2,  5])

In [12]:
x_t.shape

(3,)

In [13]:
# ...but it does we use nested "matrix-style" brackets: 
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [14]:

y.shape

(1, 3)

In [15]:
y.ndim

2

In [16]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent: 
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [17]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [18]:
# Column vector can be transposed back to original row vector: 
y_t.T 

array([[25,  2,  5]])

In [19]:
y_t.T.shape

(1, 3)

Zero Vectors

In [20]:
z = np.zeros(3) 
z

array([0., 0., 0.])

Vectors in PyTorch and TensorFlow

In [22]:
import torch

In [24]:
import tensorflow as tf

In [23]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [25]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>